stages:
  - build
  - test
  - format

### Build stage
#
# build the project
build:
  image: gcc:latest
  stage: build

  script:
    - echo "Build the project"
    - make

### Test stages
#
# run the unit tests
test_unit:
  image: gcc:latest
  stage: test

  dependencies:
    - build

  script:
    - echo "Run the tests"
    - make test

# run the tests with valgrind
# to check for memory leaks
memory_leaks:
  image: yag000/c_tools:latest
  stage: test

  dependencies:
    - build

  script:
    - echo "Run the tests with valgrind"
    - make test-valgrind

### Format stage
#
# check the code Format
format:
  image: yag000/c_tools:latest
  stage: format

  script:
    - echo "Check the code format"
    - make check-format
